# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd9999d583688ac686b44feaafe838fd20e76177f4ef0d534289fb5f75c17dd4d16aa6299da0bcec27b0ad36a171a37e41c20308fd5db80cef2938874e356274

test:
  secret_key_base: 5f25546a2436ca06c54f75b7d1b87f51225c10aba546ad9ec10b73818d67ebc582706b31c56978d800f803779722487743763158431629804adee32e0f473867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
